# ============================================
# $Id: Makefile,v 1.1 2008/08/06 15:11:52 eric Exp $
#
# ============================================

SUBDIR= Actions Images programs

pages_not_xml = info.xml
pages_not_php = fam2po.php po2js.php

include $(utildir)/PubRule

clean:
	/bin/rm -f *.*~ info.xml
