# ============================================
# $Id: Makefile,v 1.1 2008/08/06 15:11:52 eric Exp $
#
# ============================================

SUBDIR= Actions Images programs
include $(utildir)/PubRule

clean:
	/bin/rm -f *.*~ info.xml
